HeartDiseasePrediction/Controllers/PrescriptionController.cs
using Database.Entities;
using HeartDiseasePrediction.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
using Repositories;
using Repositories.ViewModel;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HeartDiseasePrediction.Controllers
{
	public class PrescriptionController : Controller
	{
		private readonly IToastNotification _toastNotification;
		private readonly IUnitOfWork _unitOfWork;
		private readonly AppDbContext _context;
		private readonly IWebHostEnvironment _webHostEnvironment;
		public PrescriptionController(IToastNotification toastNotification,
			AppDbContext context, IUnitOfWork unitOfWork)
		{
			_toastNotification = toastNotification;
			_unitOfWork = unitOfWork;
			_context = context;
		}

		//Get All Prescriptions By User ID
		[Authorize(Roles = "Doctor")]
		public async Task<IActionResult> Index()
		{
			string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string userRole = User.FindFirstValue(ClaimTypes.Role);
			var prescriptions = await _unitOfWork.prescriptions.GetPrescriptionByUserId(userId, userRole);
			return View(prescriptions);
		}

		//Get All Prescriptions
		[Authorize(Roles = "User")]
		public async Task<IActionResult> GetPrescriptions()
		{
			string PatientEmail = User.FindFirstValue(ClaimTypes.Email);
			string userRole = User.FindFirstValue(ClaimTypes.Role);
			var prescriptions = await _unitOfWork.prescriptions.GetPrescriptionByEmail(PatientEmail, userRole);
			return View(prescriptions);
		}
		//Search for Prescriptions
		[HttpPost]
		public async Task<IActionResult> Index(long search)
		{
			var prescriptions = await _unitOfWork.prescriptions.FilterPrescriptions(search);
			return View(prescriptions);
		}

		//get Prescription details
		[AllowAnonymous]
		public async Task<IActionResult> PrescriptionDetails(int id)
		{
			try
			{
				var prescription = await _unitOfWork.prescriptions.GetPrescription(id);
				if (prescription == null)
					return View("NotFound");

				var prescriptionVM = new PrescriptionVM
				{
					MedicineName = prescription.MedicineName,
					PatientSSN = prescription.PatientSSN,
					date = prescription.date,
					ApDoctorId = prescription.ApDoctorId,
					DoctorEmail = prescription.DoctorEmail,
					PatientEmail = prescription.PatientEmail,
					DoctorId = prescription.DoctorId,
					DoctorName = prescription.Doctor.Name,
				};
				return View(prescriptionVM);
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
		}

		//Create Prescriptions
		[Authorize(Roles = "Doctor")]
		public async Task<IActionResult> Create()
		{
			var doctorDropDownList = await _unitOfWork.prescriptions.GetDoctorDropDownsValues();
			ViewBag.Doctor = new SelectList(doctorDropDownList.doctors, "Id", "Name");
			return View();
		}
		[Authorize(Roles = "Doctor")]
		[HttpPost]
		public async Task<IActionResult> Create(PrescriptionViewModel model)
		{
			try
			{
				var doctorDropDownList = await _unitOfWork.prescriptions.GetDoctorDropDownsValues();
				ViewBag.Doctor = new SelectList(doctorDropDownList.doctors, "Id", "Name");
				var patient = await _unitOfWork.Patients.GetPatient(model.PatientSSN);
				if (patient == null)
					return View("NotFound");
				string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
				string doctorEmail = User.FindFirstValue(ClaimTypes.Email);
				model.ApDoctorId = userId;
				model.DoctorEmail = doctorEmail;
				await _unitOfWork.prescriptions.AddPrescriptionAsync(model);
				_toastNotification.AddSuccessToastMessage("Prescription Created successfully");
				return View("CompletedSuccessfully");
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				_toastNotification.AddErrorToastMessage("An error occurred while saving the prescription.");
				return View(model);
			}
		}

		//Edit details of Prescription
		[Authorize(Roles = "Doctor")]
		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			try
			{
				var prescription = await _unitOfWork.prescriptions.GetPrescription(id);
				if (prescription == null)
					return View("NotFound");
				var doctorDropDownList = await _unitOfWork.prescriptions.GetDoctorDropDownsValues();
				ViewBag.Doctor = new SelectList(doctorDropDownList.doctors, "Id", "Name");
				var prescriptionVM = new Prescription
				{
					MedicineName = prescription.MedicineName,
					PatientSSN = prescription.PatientSSN,
					date = prescription.date,
					ApDoctorId = prescription.ApDoctorId,
					DoctorEmail = prescription.DoctorEmail,
					PatientEmail = prescription.PatientEmail,
					DoctorId = prescription.DoctorId,
				};
				return View(prescriptionVM);
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
		}
		[Authorize(Roles = "Doctor")]
		[HttpPost]
		public async Task<IActionResult> Edit(int id, Prescription model)
		{
			try
			{
				var prescription = await _unitOfWork.prescriptions.GetPrescription(id);
				if (prescription == null)
					return View("NotFound");

				var doctorDropDownList = await _unitOfWork.prescriptions.GetDoctorDropDownsValues();
				ViewBag.Doctor = new SelectList(doctorDropDownList.doctors, "Id", "Name");
				prescription.MedicineName = model.MedicineName;
				prescription.PatientSSN = model.PatientSSN;
				prescription.date = model.date;
				prescription.DoctorId = model.DoctorId;
				prescription.ApDoctorId = model.ApDoctorId;
				prescription.DoctorEmail = model.DoctorEmail;
				prescription.PatientEmail = model.PatientEmail;
				//prescription.Doctor = model.Doctor;

				_context.Prescriptions.Update(prescription);
				await _unitOfWork.Complete();
				_toastNotification.AddSuccessToastMessage("Prescription Updated successfully");
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				_toastNotification.AddErrorToastMessage("Prescription Updated Failed");
				return View();
			}
		}

		//Delete Prescription 
		[Authorize(Roles = "Doctor")]
		public IActionResult Delete(int id)
		{
			var isDeleted = _unitOfWork.prescriptions.Delete(id);
			return isDeleted ? Ok() : BadRequest();
		}
	}
}

HeartDiseasePrediction/Views/Prescription/CompletedSuccessfully.cshtml
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
﻿<div class="row">
    <div class="col-md-6 offset-3 alert alert-success align-middle text-center">
        <img src="~/images/303732192285211 (1).png" style="height:100px; width:100px; object-fit:cover" />
        <h2>Prescription was created successfully</h2>
        <hr />
        <p>Thank you!</p>
        <a class="btn btn-outline-info" asp-controller="Prescription" asp-action="Index">Ok</a>
    </div>
</div>

HeartDiseasePrediction/Views/Prescription/Create.cshtml
@model Repositories.ViewModel.PrescriptionViewModel

@{
    ViewData["Title"] = "Create Prescription Page";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<section class="book_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col">
                <form asp-action="Create">
                    <h4>
                        Create <span>Prescription</span>
                    </h4>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-row ">
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.PatientSSN" class="control-label"></label>
                            <input asp-for="@Model.PatientSSN" type="number" class="form-control" id="inputFullName" placeholder="Enter Patient SSN">
                            <span asp-validation-for="@Model.PatientSSN" class="text-danger"></span>
                        </div>
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.PatientEmail" class="control-label"></label>
                            <input asp-for="@Model.PatientEmail" type="text" class="form-control" id="inputDoctorEmail" placeholder="Enter Patient Email">
                            <span asp-validation-for="@Model.PatientEmail" class="text-danger"></span>
                        </div>
                        @*<div class="form-group col-lg-4">
                            <label asp-for="@Model.DoctorId" class="control-label"></label>
                            <input asp-for="@Model.DoctorId" type="number" class="form-control" id="inputDoctorId" placeholder="Enter Doctor ID">
                            <span asp-validation-for="@Model.DoctorId" class="text-danger"></span>
                        </div>*@
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.DoctorId">Doctor Name</label>
                            <select asp-for="@Model.DoctorId" class="form-control wide" id="inputDoctor" asp-items="ViewBag.Doctor">
                                <option value="NoSelected ">--Please Select Doctor-- </option>
                            </select>
                            <span asp-validation-for="@Model.DoctorId" class="text-danger"></span>
                        </div>
                        @*<div class="form-group col-lg-4">
                            <label asp-for="@Model.DoctorId"></label>
                            <select asp-for="@Model.DoctorId" class="form-control wide" id="inputDoctor" asp-items="ViewBag.Doctor">
                                <option value="NoSelected ">--Please Select Docotr-- </option>
                            </select>
                            <span asp-validation-for="@Model.DoctorId" class="text-danger"></span>
                        </div>*@
                        @*<div class="form-group col-lg-4">
                            <label asp-for="@Model.date"></label>
                            <div class="input-group date" id="inputDate" data-date-format="mm-dd-yyyy">
                                <input asp-for="@Model.date" type="text" class="form-control" readonly>
                                <span class="input-group-addon date_icon">
                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                </span>
                            </div>
                        </div>*@
                    </div>
                    <div class="form-row ">
                        <div class="form-group col-lg-6">
                            <label asp-for="@Model.MedicineName" class="control-label"></label>
                            <textarea asp-for="@Model.MedicineName" class="form-control-range" rows="4" cols="30" placeholder="Enter Medician"></textarea>
                            <span asp-validation-for="@Model.MedicineName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="btn-box">
                        <button type="submit" class="btn ">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HeartDiseasePrediction/Views/Prescription/Edit.cshtml
@model Database.Entities.Prescription

@{
    ViewData["Title"] = "Prescription Update Page";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<section class="book_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col">
                <form asp-action="Edit">
                    <h4>
                        Update <span>Prescription</span>
                    </h4>
                    <div class="form-row ">
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.PatientSSN" class="control-label"></label>
                            <input asp-for="@Model.PatientSSN" type="text" class="form-control" id="inputPatientSSN">
                        </div>
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.date"></label>
                            <input asp-for="@Model.date" type="datetime" class="form-control">
                        </div>
                       
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.DoctorId" hidden class="control-label"></label>
                            <input asp-for="@Model.DoctorId" hidden type="text" class="form-control" id="inputDoctorId">
                        </div><div class="form-group col-lg-4">
                            <label asp-for="@Model.DoctorEmail" hidden class="control-label"></label>
                            <input asp-for="@Model.DoctorEmail" hidden type="text" class="form-control" id="inputDoctorEmail">
                        </div>
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.ApDoctorId" hidden class="control-label"></label>
                            <input asp-for="@Model.ApDoctorId" hidden type="text" class="form-control" id="inputApDoctorId">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.PatientEmail" class="control-label"></label>
                            <input asp-for="@Model.PatientEmail" type="text" class="form-control" id="inputPatientEmail">
                        </div>
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.DoctorId">Doctor Name</label>
                            <select asp-for="@Model.DoctorId" class="form-control wide" id="inputDoctor" asp-items="ViewBag.Doctor">
                                <option value="NoSelected ">--Please Select Doctor-- </option>
                            </select>
                            <span asp-validation-for="@Model.DoctorId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-lg-6">
                            <label asp-for="@Model.MedicineName" class="control-label"></label>
                            <textarea asp-for="@Model.MedicineName" class="form-control-range"
                                      rows="4"
                                      cols="30"></textarea>
                        </div>
                    </div>
                    <div class="btn-box">
                        <button type="submit" class="btn ">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HeartDiseasePrediction/Views/Prescription/EditPrescription.cshtml
@model Database.Entities.Prescription

@{
    ViewData["Title"] = "Prescription Update Page";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<section class="book_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col">
                <form asp-action="EditPrescription">
                    <h4>
                        Update <span>Prescription</span>
                    </h4>
                    <div class="form-row ">
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.PatientSSN" class="control-label"></label>
                            <input asp-for="@Model.PatientSSN" type="text" class="form-control" id="inputPatientSSN">
                        </div>
                        <div class="form-group col-lg-3">
                            <label asp-for="@Model.date"></label>
                            <input asp-for="@Model.date" type="datetime" class="form-control">
                        </div>
                        <div class="form-group col-lg-4">
                            <label asp-for="@Model.DoctorId" hidden class="control-label"></label>
                            <input asp-for="@Model.DoctorId" hidden type="text" class="form-control" id="inputPatientSSN">
                        </div>
                    </div>
                    <div class="form-row ">
                        <div class="form-group col-lg-6">
                            <label asp-for="@Model.MedicineName" class="control-label"></label>
                            <textarea asp-for="@Model.MedicineName" class="form-control-range" 
                            rows="4" 
                            cols="30"></textarea>
                        </div>
                    </div>
                    <div class="btn-box">
                        <button type="submit" class="btn ">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HeartDiseasePrediction/Views/Prescription/GetPrescriptions.cshtml
@model List<Database.Entities.Prescription>

@{
	ViewData["Title"] = "Prescriptions List Page";
	Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<style>
	.card {
		box-shadow: 0px 4px 8px 0px #7986CB;
	}
</style>
<section class="card card-body bg-light " style="margin:30px 80px">
	<div class="container mt-4">
		<div class="row">
			<div class="col-md-10 offset-md-1">
				<div class="main-body">
					<nav aria-label="breadcrumb" class="main-breadcrumb ">
						<ol class="breadcrumb">
							<li class="breadcrumb-item">Prescriptions</li>
							<li class="breadcrumb-item">List</li>
							<li class="breadcrumb-item active" aria-current="page">List of Prescriptions</li>
						</ol>
					</nav>
				</div>
				<div class="form-inline justify-content-end my-2 my-lg-1 d-flex">
					<div>
						@using (Html.BeginForm("Index", "Prescription", FormMethod.Post))
						{
							@Html.TextBox("search",null,new{@class="form-control",placeholder="Search here...",style="margin:5px 0px 5px 5px"})
							<button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> </button>
						}
					</div>
				</div>
				@if (!Model.Any())
				{
					<div class="alert alert-warning" role="alert">
						No Prescriptions Found
					</div>
				}
				else
				{
					<table class="table table-hover table-responsive table-striped">
						<thead>
							<tr class="text-center bg-dark text-light">
								<th>#</th>
								<th>Medicine Name</th>
								<th>Date</th>
								@if (User.Identity.IsAuthenticated && User.IsInRole("User"))
								{
									<th>Doctor</th>
								}
								@*@if (User.Identity.IsAuthenticated && User.IsInRole("Doctor"))
								{
									<th>Patient</th>
								}*@
								<th>Patient SSN</th>
								<th>
								</th>
								@*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
							{
							<th>Action</th>
							}*@

							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model)
							{
								<tr>
									<td class="align-middle text-center counterColumn">
									</td>
									<td class="align-middle text-center">
										@item.MedicineName
									</td>
									<td class="align-middle text-center">
										@item.date.ToString("dd MMM yy")
									</td>
									@if (User.Identity.IsAuthenticated && User.IsInRole("User"))
									{
										<td class="align-middle text-center">
											@item.Doctorr.FirstName @item.Doctorr.LastName
										</td>
									}
								@*	@if (User.Identity.IsAuthenticated && User.IsInRole("Doctor"))
									{
										<td class="align-middle text-center">
											@item.Patientt.FirstName @item.Patientt.LastName
										</td>
									}*@
									<td class="align-middle text-center">
										@item.PatientSSN
									</td>
									@if (User.Identity.IsAuthenticated && User.IsInRole("User"))
									{
										<td class="align-middle text-center">
											<a class="btn btn-outline-info" asp-controller="Prescription" asp-action="PrescriptionDetails" asp-route-id="@item.Id"><i class="fa fa-eye"></i> Details</a>
										</td>
									}
								</tr>
							}
						</tbody>
					</table>
				}
			</div>
		</div>
	</div>
</section>
<script>
	function ConfirmDelete() {
		document.getElementById("");
		var accept = confirm("Are You Sure to delete this Prescription?");
		if (accept == false) {
			event.preventDefault();
		}
	}
	document.addEventListener("DOMContentLoaded", function () {
		var counterCells = document.querySelectorAll(".counterColumn");
		var counter = 1;
		counterCells.forEach(function (cell) {
			cell.textContent = counter++;
		});
	});
</script>

HeartDiseasePrediction/Views/Prescription/Index.cshtml
@model List<Database.Entities.Prescription>

@{
    ViewData["Title"] = "Prescriptions List Page";
	Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<style>
	.card {
		box-shadow: 0px 4px 8px 0px #7986CB;
	}
</style>
<section class="card card-body bg-light " style="margin:25px 80px">
	<div class="container mt-4">
		<div class="row">
			<div class="col-md-12 offset-md-0">
				<div class="main-body">
					<nav aria-label="breadcrumb" class="main-breadcrumb ">
						<ol class="breadcrumb">
							<li class="breadcrumb-item">Prescriptions</li>
							<li class="breadcrumb-item">List</li>
							<li class="breadcrumb-item active" aria-current="page">List of Prescriptions</li>
						</ol>
					</nav>
				</div>
				<div class="form-inline justify-content-between my-2 my-lg-1 d-flex">
					<div class="modal fade" id="DeleteModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<form id="saveForm" method="post"></form>
								<div class="modal-header">
									<h5 class="modal-title" id="exampleModalLabel">Delete Prescription</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<h3>Are you sure to delte this Prescription?</h3>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary btnCancel" data-dismiss="modal">Cancel</button>
									<button id="btnDelete" type="button" class="btn btn-danger ">Delete</button>
								</div>
							</div>
						</div>
					</div>
					<a asp-controller="Prescription" asp-action="Create" class="btn btn-success">
						<i class="fa fa-plus-circle"></i> Add New
					</a>
					<div>
						@using (Html.BeginForm("Index", "Prescription", FormMethod.Post))
						{
							@Html.TextBox("search",null,new{@class="form-control",placeholder="Search here...",style="margin:5px 0px 5px 5px"})
							<button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> </button>
						}
					</div>
				</div>
				<span id="Message" class="d-none">@TempData["Message"]</span>
				@if (!Model.Any())
				{
					<div class="alert alert-warning" role="alert">
						No Prescriptions Found
					</div>
				}
				else
				{
					<input type="hidden" id="PrescriptionId" />
					<table class="table table-hover table-responsive table-striped">
						<thead>
							<tr class="text-center bg-dark text-light">
								<th>#</th>
								@*<th>Medicine Name</th>*@
								<th>Date</th>
								@if (User.Identity.IsAuthenticated && User.IsInRole("User"))
								{
									<th>Doctor</th>
								}
								@if (User.Identity.IsAuthenticated && User.IsInRole("Doctor"))
								{
									<th>Patient</th>
									@*<th>Patient Name</th>*@
								}
								<th>Patient SSN</th>
								<th>
								</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model)
							{
								<tr>
									<td class="align-middle text-center counterColumn">
									</td>
									@*<td class="align-middle text-center">
										@item.MedicineName
									</td>*@
									<td class="align-middle text-center">
										@item.date.ToString("dd MMM yy")
									</td>
									@if (User.Identity.IsAuthenticated && User.IsInRole("User"))
									{
										<td class="align-middle text-center">
											@item.Doctorr.FirstName @item.Doctorr.LastName
										</td>
									}
									@if (User.Identity.IsAuthenticated && User.IsInRole("Doctor"))
									{
										<td class="align-middle text-center">
											@item.PatientEmail
										</td>
										@*<td class="align-middle text-center">
											@item.Patient.User.FirstName 
										</td>*@
									}
									<td class="align-middle text-center">
										@item.PatientSSN
									</td>
									@if (User.Identity.IsAuthenticated && User.IsInRole("Doctor"))
									{
										<td class="align-middle text-center" style="padding-left:20px">
											<a class="btn btn-outline-primary"  asp-controller="Prescription" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pencil-square"></i> Edit</a> |
											<a class="btn btn-outline-info" asp-controller="Prescription" asp-action="PrescriptionDetails" asp-route-id="@item.Id"><i class="fa fa-eye"></i> Details</a> |
											<a href="javascript:;" class="btn btn-danger rounded rounded-3 js-delete" data-id="@item.Id"><i class="fa fa-trash"></i> Delete</a>
										</td>
									}
									@if (User.Identity.IsAuthenticated && User.IsInRole("User"))
									{
										<td class="align-middle text-center">
											<a class="btn btn-outline-info" asp-controller="Prescription" asp-action="PrescriptionDetails" asp-route-id="@item.Id" ><i class="fa fa-eye"></i> Details</a>
										</td>
									}
								</tr>
							}
						</tbody>
					</table>
				}
			</div>
		</div>
	</div>
</section>
@section Scripts{
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
	<script>
		$(document).ready(function () {
			$('.js-delete').on('click', function () {
				var btn = $(this);

				const swal = Swal.mixin({
					customClass: {
						confirmButton: 'btn btn-danger mx-2',
						cancelButton: 'btn btn-light'
					},
					buttonsStyling: false
				});

				swal.fire({
					title: 'Are you sure that you need to delete this Prescription?',
					text: "You won't be able to revert this!",
					icon: 'warning',
					showCancelButton: true,
					confirmButtonText: 'Yes, delete it!',
					cancelButtonText: 'No, cancel!',
					reverseButtons: true
				}).then((result) => {
					if (result.isConfirmed) {
						$.ajax({
							url: `/Prescription/Delete/${btn.data('id')}`,
							method: 'DELETE',
							success: function () {
								swal.fire(
									'Deleted!',
									'Prescription has been deleted.',
									'success'
								);

								btn.parents('tr').fadeOut();
							},
							error: function () {
								swal.fire(
									'Oooops...',
									'Something went wrong.',
									'error'
								);
							}
						});
					}
				});
			});
		});

		document.addEventListener("DOMContentLoaded", function () {
			var counterCells = document.querySelectorAll(".counterColumn");
			var counter = 1;
			counterCells.forEach(function (cell) {
				cell.textContent = counter++;
			});
		});
	</script>
}