HeartDiseasePrediction/Controllers/AppointmentController.cs
using Database.Entities;
using HeartDiseasePrediction.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using Repositories;
using Repositories.Interfaces;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HeartDiseasePrediction.Controllers
{
	public class AppointmentController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IToastNotification _toastNotification;

		public AppointmentController(IUnitOfWork unitOfWork, IToastNotification toastNotification,
			IFileRepository fileRepository)
		{
			_unitOfWork = unitOfWork;
			_toastNotification = toastNotification;
		}

		//Get All Appointments by User ID
		[Authorize(Roles = "User")]
		public async Task<IActionResult> Index()
		{
			string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string userRole = User.FindFirstValue(ClaimTypes.Role);
			var appointments = await _unitOfWork.appointments.GetAppointmenByUserId(userId, userRole);
			return View(appointments);
		}

		//Get All Appointments by Email
		[Authorize(Roles = "Doctor")]
		public async Task<IActionResult> GetAppointmentByEmail()
		{
			string doctorEmail = User.FindFirstValue(ClaimTypes.Email);
			string userRole = User.FindFirstValue(ClaimTypes.Role);
			var appointments = await _unitOfWork.appointments.GetAppointmenByEmail(doctorEmail, userRole);
			return View(appointments);
		}

		//Get All Appointments by User ID
		[Authorize(Roles = "Doctor")]
		public async Task<IActionResult> GetMessageById()
		{
			string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string userRole = User.FindFirstValue(ClaimTypes.Role);
			var messages = await _unitOfWork.appointments.GetMessageByUserId(userId, userRole);
			return View(messages);
		}

		//Get All Appointments by Email
		[Authorize(Roles = "User")]
		public async Task<IActionResult> GetMessagetByEmail()
		{
			string patientEmail = User.FindFirstValue(ClaimTypes.Email);
			string userRole = User.FindFirstValue(ClaimTypes.Role);
			var messages = await _unitOfWork.appointments.GetMessageByEmail(patientEmail, userRole);
			return View(messages);
		}

		//Create Appointment
		public async Task<IActionResult> Create(int id)
		{
			var doctor = await _unitOfWork.Doctors.GetDoctor(id);
			if (doctor == null)
				return View("NotFound");
			var DoctorDetail = new BookAppointmentViewModel
			{
				FirstName = doctor.User.FirstName,
				LastName = doctor.User.LastName,
				BirthDate = doctor.User.BirthDate,
				Email = doctor.User.Email,
				Gender = doctor.User.Gender,
				PhoneNumber = doctor.User.PhoneNumber,
				Name = doctor.Name,
				Location = doctor.Location,
				Price = doctor.Price,
				//ProfileImg = doctor.User.ProfileImg,
			};
			return View(DoctorDetail);
		}
		[Authorize(Roles = "User")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(int id, BookAppointmentViewModel model)
		{
			var doctor = await _unitOfWork.Doctors.GetDoctor(id);
			if (doctor == null)
				return View("NotFound");

			string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string patientEmail = User.FindFirstValue(ClaimTypes.Email);
			model.PatientID = userId;
			model.PatientEmail = patientEmail;
			var appointment = new Appointment()
			{
				PatientID = model.PatientID,
				PateintName = model.PateintName,
				PatientEmail = model.PatientEmail,
				DoctorEmail = doctor.User.Email,
				date = model.Date,
				Time = model.Time,
				PhoneNumber = model.PatientPhone,
				PatientSSN = model.PatientSSN,
				DoctorId = doctor.Id,
			};

			await _unitOfWork.appointments.AddAsync(appointment);
			await _unitOfWork.Complete();
			_toastNotification.AddSuccessToastMessage("Appointment Created Successfully");
			return View("CompletedSuccessfully");
		}

		//Accept Appointment
		[Authorize(Roles = "Doctor")]
		public async Task<IActionResult> AcceptsAppointment(int id, MessageViewModel model)
		{
			var appointment = await _unitOfWork.appointments.GetAppointment(id);
			if (appointment == null)
				return View("NotFound");
			string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string doctorEmail = User.FindFirstValue(ClaimTypes.Email);
			model.DoctorId = userId;
			model.DoctorEmail = doctorEmail;
			var message = new Message
			{
				Messages = "Your Appointment is Accepted",
				Date = DateTime.Now,
				PatientEmail = appointment.PatientEmail,
				DoctorEmail = doctorEmail,
				DoctorId = userId,
			};
			await _unitOfWork.appointments.AddMessageAsync(message);
			await _unitOfWork.Complete();
			_toastNotification.AddSuccessToastMessage($"Message has sent successfully");
			return RedirectToAction("Index");
		}

		//Cancel Appointment by doctor
		[Authorize(Roles = "Doctor")]
		public async Task<IActionResult> CanceledAppointment(int id, MessageViewModel model)
		{
			var appointment = _unitOfWork.appointments.Get_Appointment(id);
			string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string doctorEmail = User.FindFirstValue(ClaimTypes.Email);
			model.DoctorId = userId;
			model.DoctorEmail = doctorEmail;
			var message = new Message
			{
				Messages = "Sorry,Your Appointment is Canceled because Doctor is busy in this time",
				Date = model.Date,
				PatientEmail = appointment.PatientEmail,
				DoctorEmail = doctorEmail,
				DoctorId = userId,
			};
			await _unitOfWork.appointments.AddMessageAsync(message);
			await _unitOfWork.Complete();
			var isDeleted = _unitOfWork.appointments.Canceled(id);
			return isDeleted ? Ok() : BadRequest();
		}

		//Cancel appointment by user
		[Authorize(Roles = "User")]
		public IActionResult Canceled(int id)
		{
			var isDeleted = _unitOfWork.appointments.Canceled(id);
			return isDeleted ? Ok() : BadRequest();
		}


		[Authorize(Roles = "User")]
		public async Task<IActionResult> DoctorDetailsWithAppointment(int id)
		{
			try
			{
				var doctor = await _unitOfWork.Doctors.GetDoctor(id);
				if (doctor == null)
					return View("NotFound");

				var DoctorDetail = new DoctorVM
				{
					FirstName = doctor.User.FirstName,
					LastName = doctor.User.LastName,
					BirthDate = doctor.User.BirthDate,
					Email = doctor.User.Email,
					Gender = doctor.User.Gender,
					PhoneNumber = doctor.User.PhoneNumber,
					Name = doctor.Name,
					Location = doctor.Location,
					Price = doctor.Price,
					//ProfileImg = doctor.User.ProfileImg,
				};
				return View(DoctorDetail);
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
		}

	}
}

HeartDiseasePrediction/Controllers/PatientController.cs
using Database.Entities;
using HeartDiseasePrediction.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using Repositories;
using Repositories.Interfaces;
using System;
using System.Threading.Tasks;

namespace HeartDiseasePrediction.Controllers
{
	public class PatientController : Controller
	{
		private readonly IToastNotification _toastNotification;
		private readonly IUnitOfWork _unitOfWork;
		private readonly AppDbContext _context;
		private readonly IWebHostEnvironment _webHostEnvironment;
		private readonly IFileRepository _fileRepository;
		public PatientController(IToastNotification toastNotification, AppDbContext context,
			IUnitOfWork unitOfWork, IFileRepository fileRepository)
		{
			_context = context;
			_unitOfWork = unitOfWork;
			_fileRepository = fileRepository;
			_toastNotification = toastNotification;
		}
		//get all Patients in list
		public async Task<IActionResult> Index()
		{
			var patients = await _unitOfWork.Patients.GetPatients();
			return View(patients);
		}
		[HttpPost]
		public async Task<IActionResult> Index(string search)
		{
			var patients = await _unitOfWork.Patients.FilterPatients(search);
			return View(patients);
		}

		//public async Task<ActionResult> Details(int id)
		//{
		//	var viewModel = new PatientDetailViewModel()
		//	{
		//		Patient = await _unitOfWork.Patients.GetPatient(id),
		//		Appointments = await _unitOfWork.appointments.GetAppointmentWithPatient(id),
		//		Attendances = await _unitOfWork.attendances.GetAttendance(id),
		//		CountAppointments = await _unitOfWork.appointments.CountAppointments(id),
		//		CountAttendance = await _unitOfWork.attendances.CountAttendances(id)
		//	};
		//	return View("Details", viewModel);
		//}

		//get Patient details
		public async Task<IActionResult> PatientDetails(long ssn)
		{
			try
			{
				var patient = await _unitOfWork.Patients.GetPatient(ssn);
				if (patient == null)
					return View("NotFound");

				var patientVM = new PatientVM
				{
					SSN = patient.SSN,
					Insurance_No = patient.Insurance_No,
					FirstName = patient.User.FirstName,
					LastName = patient.User.LastName,
					BirthDate = patient.User.BirthDate,
					Email = patient.User.Email,
					Gender = patient.User.Gender,
					PhoneNumber = patient.User.PhoneNumber,
					ProfileImg = patient.User.ProfileImg,
				};
				return View(patientVM);

			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
		}

		//Edit Patient
		[HttpGet]
		public async Task<IActionResult> Edit(long ssn)
		{
			try
			{
				var patient = await _unitOfWork.Patients.GetPatient(ssn);
				if (patient == null)
					return View("NotFound");

				var patientVM = new PatientVM
				{
					FirstName = patient.User.FirstName,
					LastName = patient.User.LastName,
					BirthDate = patient.User.BirthDate,
					Insurance_No = patient.Insurance_No,
					SSN = patient.SSN,
					//Insurance_No = patient.User.Insurance_No,
					Email = patient.User.Email,
					Gender = patient.User.Gender,
					PhoneNumber = patient.User.PhoneNumber,
					ProfileImg = patient.User.ProfileImg,
				};
				return View(patientVM);

			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
		}
		[HttpPost]
		public async Task<IActionResult> Edit(long ssn, PatientVM model)
		{
			try
			{
				var patient = await _unitOfWork.Patients.GetPatient(ssn);
				if (patient == null)
					return View("NotFound");

				//string wwwRootPath = _webHostEnvironment.WebRootPath;
				//string fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
				//string extension = Path.GetExtension(model.ImageFile.FileName);
				//model.ProfileImg = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
				//string path = Path.Combine(wwwRootPath + "/Upload", fileName);

				//using (var fileStream = new FileStream(path, FileMode.Create))
				//{
				//    await model.ImageFile.CopyToAsync(fileStream);
				//}
				patient.User.PhoneNumber = model.PhoneNumber;
				patient.User.Email = model.Email;
				patient.User.FirstName = model.FirstName;
				patient.User.LastName = model.LastName;
				patient.User.BirthDate = model.BirthDate;
				patient.User.Gender = model.Gender;
				patient.Insurance_No = model.Insurance_No;
				patient.User.Insurance_No = model.Insurance_No;
				patient.User.SSN = model.SSN;
				patient.SSN = model.SSN;
				//doctor.User.ProfileImg = model.ProfileImg;

				_context.Patients.Update(patient);
				await _unitOfWork.Complete();
				_toastNotification.AddSuccessToastMessage("Patient Updated successfully");
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				_toastNotification.AddErrorToastMessage("Patient Updated Failed");
				return View();
			}
		}

		////Delete Patient 
		//public async Task<IActionResult> DeletePatient(long ssn)
		//{
		//	var patient = _unitOfWork.Patients.Get_Patient(ssn);
		//	if (patient == null)
		//		return View("NotFound");
		//	//var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "/Upload", patient.User.ProfileImg);
		//	try
		//	{
		//		//if (System.IO.File.Exists(imagePath))
		//		//    System.IO.File.Delete(imagePath);
		//		//_patientService.Remove(patient);
		//		_unitOfWork.Patients.Remove(patient);
		//		await _unitOfWork.Complete();
		//		_toastNotification.AddSuccessToastMessage($"Patient with SSN {ssn} removed successfully");
		//		return RedirectToAction("Index");
		//	}
		//	catch (Exception ex)
		//	{
		//		TempData["errorMessage"] = ex.Message;
		//		return View();
		//	}
		//}

		//Delete Patient 
		public async Task<IActionResult> DeletePatients(long ssn)
		{
			var patient = _unitOfWork.Patients.Get_Patient(ssn);
			if (patient == null)
				return View("NotFound");
			//var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "/Upload", patient.User.ProfileImg);
			try
			{
				//if (System.IO.File.Exists(imagePath))
				//    System.IO.File.Delete(imagePath);
				//_patientService.Remove(patient);
				_unitOfWork.Patients.Deleted(patient);
				await _unitOfWork.Complete();
				_toastNotification.AddSuccessToastMessage($"Patient with SSN {ssn} removed successfully");
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				TempData["errorMessage"] = ex.Message;
				return View();
			}
		}

		public IActionResult Delete(long ssn)
		{
			var isDeleted = _unitOfWork.Patients.Delete(ssn);
			return isDeleted ? Ok() : BadRequest();
		}
	}
}

HeartDiseasePrediction/Views/Patient/Details.cshtml
@using Database.Entities
@model HeartDiseasePrediction.ViewModel.PatientDetailViewModel
@{
    ViewBag.Title = "Details";
}
<!-- load partial here-->
<div id="MyModal" class="modal fade in">
    <div class="modal-dialog " style="width: 900px;">
        <div class="modal-content">
            <div id="MyModalContent"></div>
        </div>
    </div>
</div>


<div class="page-title">
    <div class="title_left">
        <h3>Details</h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            @*<div class="x_title">
            <h2>Patient Details </h2>
            <ul class="nav navbar-right panel_toolbox">
            <li> <a href="@Url.Action("Edit", "Patients", new { id= Model.Patient.Id})" class="btn-link"><i class="fa fa-edit m-right-xs"></i>Edit</a>
            </li>
            </ul>
            <div class="clearfix"></div>
            </div>*@

            <div class="x_content">
                <div class="col-md-3 col-sm-3 col-xs-12 profile_left ">
                    <div class="profile_img">
                        <div id="crop-avatar">
                            <!-- Current avatar -->
                            <img class="img-responsive avatar-view" src="~/Content/images/user.png">
                        </div>
                    </div>
                    <h3>@Model.Patient.User.FirstName @Model.Patient.User.LastName</h3>
                    <ul class="list-unstyled user_data">
                        @*<li> <i class="fa fa-user"><strong>Token:</strong> @Model.Patient.Token</i></li>*@
                        <li> <i class="fa fa-user"><strong>Sex:</strong> @Model.Patient.User.Gender</i></li>
                        <li> <i class="fa fa-user"><strong>Age:</strong> @Model.Patient.User.Age</i></li>
                       @* <li> <i class="fa fa-user"><strong>Height:</strong> @Model.Patient.Height</i></li>
                        <li> <i class="fa fa-user"><strong>Weight:</strong> @Model.Patient.Weight</i></li>*@

                        <li>
                            <i class="fa fa-phone"></i><strong>Phone:</strong> @Model.Patient.User.PhoneNumber
                        </li>
                        @*<li class="m-top-xs">
                            <i class="fa fa-clock-o"></i><strong>Date :</strong> @Model.Patient.DateTime.ToString("MMM"), @Model.Patient.DateTime.ToString("d ")- @Model.Patient.DateTime.ToString("yyyy")-@Model.Patient.DateTime.ToString("HH:mm")

                        </li>*@
                    </ul>
                    <a href="@Url.Action("Edit", "Patient", new { id= Model.Patient.SSN})" class="btn btn-success"><i class="fa fa-edit m-right-xs"></i>Edit</a>

                    <br />
                </div>
                <div class="col-md-9 col-sm-9 col-xs-12">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <span class="section"> Appointment</span>
                        <a id="patientID" data-appointment-id="@Model.Patient.SSN" href="#"> Patient Appointment</a>  <span class="badge badge-error">@Model.CountAppointments</span> @if (User.IsInRole("Admin"))
                        {
                            <a href="@Url.Action("Create", "Appointment", new {id = Model.Patient.SSN})"><i class="fa fa-plus"></i></a>
                        }
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <span class="section">Attendance </span>
                        <a id="attendanceID" data-attendance-id="@Model.Patient.SSN" href="#"> Lab Attendance </a> <span class="badge badge-error">@Model.CountAttendance</span> <a href="@Url.Action("Create", "Attendance", new { id=Model.Patient.SSN})"> <i class="fa fa-plus"></i></a>
                    </div>
                    @*<div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                    <li role="presentation" class="active">
                    <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Appointment history</a>

                    </li>
                    <li role="presentation" class="">
                    <a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Attendance history</a>
                    </li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                    <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                    <!-- start appointment history -->
                    <table class="data table table-striped no-margin dataTables">
                    <thead>
                    <tr>
                    <th>Doctor</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Details</th>
                    <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model.Appointments)
                    {
                    <tr>
                    <td>@item.Doctor.Name</td>
                    <td>@item.StartDateTime.ToString("MMM"),@item.StartDateTime.ToString("d ")-@item.StartDateTime.ToString("yyyy")</td>
                    <td>@item.StartDateTime.ToString("HH:mm")</td>
                    <td>@item.Detail</td>
                    <td>
                    @{
                    if (item.Status == true)
                    {
                    <a href="#" style="padding: 3px 10px 3px 10px; background-color:green " class="badge" readonly>Approved</a>
                    }
                    else
                    {
                    <a href="#" style="padding: 3px 10px 3px 10px; background-color:greenyellow " class="badge" readonly>Pending</a>
                    }
                    }
                    </td>

                    </tr>

                    }
                    </tbody>
                    </table>
                    <!-- end appointment history -->
                    </div>
                    <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                    <table class="data table table-striped no-margin dataTables">
                    <thead>
                    <tr>
                    <th>Clinic Remarks</th>
                    <th>Diagnosis</th>
                    <th>Second Diagnosis</th>
                    <th>Third Diagnosis</th>
                    <th>Therapy</th>
                    <th>Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model.Attendances)
                    {
                    <tr>
                    <td>@item.ClinicRemarks</td>
                    <td>@item.Diagnosis</td>
                    <td>@item.SecondDiagnosis</td>
                    <td>@item.ThirdDiagnosis</td>
                    <td>@item.Therapy</td>
                    <td>@item.Date.ToString("MMM"), @item.Date.ToString("d ")-@item.Date.ToString("yyyy")</td>
                    </tr>

                    }
                    </tbody>
                    </table>
                    </div>
                    </div>
                    </div>*@
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $("#patientID").on("click", function () {
                var link = $(this);
                $.ajaxSetup({ cache: false });
                var detailUrl = "/Appointments/Details/" + link.attr("data-appointment-id");
                $("#MyModalContent").load(detailUrl, function () {
                    $("#MyModal").modal({
                        keyboard: false
                    }, 'show');

                });
                return false;
            });
            $("#attendanceID").on("click", function () {
                var link = $(this);
                $.ajaxSetup({ cache: false });
                var detailUrl = "/Attendances/Details/" + link.attr("data-attendance-id");
                $("#MyModalContent").load(detailUrl, function () {
                    $("#MyModal").modal({
                        keyboard: false
                    }, 'show');

                });
                return false;
            });


        });

        $('.dataTables').DataTable({
            "scrollY": "300px",
            "scrollCollapse": true,
            "paging": false,
            "filter": false,
            "info": false
        });
    </script>

}

HeartDiseasePrediction/Views/Patient/Index.cshtml
@model IEnumerable<Database.Entities.Patient>

@{
	ViewData["Title"] = "Patients List Page";
	Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<style>
	.card {
		box-shadow: 0px 4px 8px 0px #7986CB;
	}
</style>
<section class="card card-body bg-light " style="margin:20px 35px">
	<div class="container mt-4">
		<div class="row">
			<div class="col-md-13 offset-md-0">
				<div class="main-body">
					<nav aria-label="breadcrumb" class="main-breadcrumb ">
						<ol class="breadcrumb">
							<li class="breadcrumb-item">Patients</li>
							<li class="breadcrumb-item">List</li>
							<li class="breadcrumb-item active" aria-current="page">List of Patients</li>
						</ol>
					</nav>
				</div>
				<div class="form-inline justify-content-between my-2 my-lg-1 d-flex">
					<div class="modal fade" id="DeleteModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<form id="saveForm" method="post"></form>
								<div class="modal-header">
									<h5 class="modal-title" id="exampleModalLabel">Delete Prescription</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<h3>Are you sure to delte this Patient?</h3>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary btnCancel" data-dismiss="modal">Cancel</button>
									<button id="btnDelete" type="button" class="btn btn-danger ">Delete</button>
								</div>
							</div>
						</div>
					</div>
					<a asp-controller="Account" asp-action="RegisterOfUser" class="btn btn-success">
						<i class="fa fa-plus-circle"></i> Add New
					</a>
					@*<input type = "button" value="Alert message" name="alertMessage" id="btnAlertMessage"/>*@
					<div >
						@using (Html.BeginForm("Index", "Patient", FormMethod.Post))
						{
							@Html.TextBox("search",null,new{@class="form-control",placeholder="Search here...",style="margin:5px 0px 5px 5px"})
							<button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> </button>
						}
					</div>
				</div>
				@if (!Model.Any())
				{
					<div class="alert alert-warning" role="alert">
						No Patients Found
					</div>
				}
				else
				{
					<input type="hidden" id="PatientId" />
					<table class="table table-hover table-responsive table-striped" id="Patients">
						<thead>
							<tr class="text-center bg-dark text-light">
								<th>#</th>
								<th>SSN</th>
								@*<th>InsuranceNo</th>*@
								<th>Email</th>
								<th>FirstName</th>
								<th>LastName</th>
								@*<th>Age</th>*@
								@*<th>Phone</th>*@
								<th>
								</th>

							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model)
							{
								<tr>
									@*<td class="align-middle text-center">
							<img class="rounded-circle" src="@item.ProfileImg" alt="@item.FullName" style="max-width:150px">
							</td>*@
									<td class="align-middle text-center counterColumn">
									</td>
									<td class="align-middle text-center">
										@item.SSN
									</td>
									@*<td class="align-middle text-center">
							@item.Insurance_No
							</td>*@
									<td class="align-middle text-center">
										@item.User.Email
									</td>
									<td class="align-middle text-center">
										@item.User.FirstName
									</td>
									<td class="align-middle text-center">
										@item.User.LastName
									</td>
									@*<td class="align-middle text-center">
										@item.User.Age
									</td>*@
									@*<td class="align-middle text-center">
										@item.User.PhoneNumber
									</td>*@
									<td class="align-middle text-center">
										<a class="btn btn-outline-primary" asp-controller="Patient" asp-action="Edit" asp-route-ssn="@item.SSN"><i class="fa fa-pencil-square"></i> Edit</a> |
										<a class="btn btn-outline-info" asp-controller="Patient" asp-action="PatientDetails" asp-route-ssn="@item.SSN"><i class="fa fa-eye"></i> Details</a> |
										<a class="btn btn-outline-danger " asp-controller="Patient" asp-action="DeletePatients" asp-route-ssn="@item.SSN" onclick="ConfirmDelete()"><i class="fa fa-trash"></i> Delete</a>
										@*<a href="javascript:;" class="btn btn-outline-danger rounded rounded-3 js-delete" data-id="@item.SSN"><i class="fa fa-trash"></i> Delete</a>*@
									</td>
								</tr>
							}
						</tbody>
					</table>
				}
			</div>
		</div>
	</div>
</section>

@section Scripts{
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
	<script>
		function ConfirmDelete() {
			document.getElementsByClassName("");
			var accept = confirm("Are You Sure to delete this patient?");
			if (accept == false) {
				event.preventDefault();
			}
		}

		$(document).ready(function () {
			$('.js-delete').on('click', function () {
				var btn = $(this);

				const swal = Swal.mixin({
					customClass: {
						confirmButton: 'btn btn-danger mx-2',
						cancelButton: 'btn btn-light'
					},
					buttonsStyling: false
				});

				swal.fire({
					title: 'Are you sure that you need to delete this Pateint?',
					text: "You won't be able to revert this!",
					icon: 'warning',
					showCancelButton: true,
					confirmButtonText: 'Yes, delete it!',
					cancelButtonText: 'No, cancel!',
					reverseButtons: true
				}).then((result) => {
					if (result.isConfirmed) {
						$.ajax({
							url: `/Patient/Delete/${btn.data('ssn')}`,
							method: 'DELETE',
							success: function () {
								swal.fire(
									'Deleted!',
									'Patient has been deleted.',
									'success'
								);

								btn.parents('tr').fadeOut();
							},
							error: function () {
								swal.fire(
									'Oooops...',
									'Something went wrong.',
									'error'
								);
							}
						});
					}
				});
			});
		});


		document.addEventListener("DOMContentLoaded", function () {
			var counterCells = document.querySelectorAll(".counterColumn");
			var counter = 1;
			counterCells.forEach(function (cell) {
				cell.textContent = counter++;
			});
		});
	</script>
}